### ISSUE TITLE
Issue when installing from conda

### ISSUE THREAD

**Issue by findalexli** [greenelab/snorkeling#106]
Hello! 

I am having the following issue with installing the condo environment from YML file. 

```
(base) MacBook-Pro-4:snorkeling alexanderli$ conda env create --file environment.yml
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gensim=3.8.1 -> python_abi=[build=*_cp37m] -> pypy[version='<0a0']
  - sqlalchemy=1.1.13
Use "conda search <package> --info" to see the dependencies for each package.
```

**Comment by ajlee21** [comment]
Hi Alex,
Excited to see that you're trying to use some of the work in this repository.  I'm actually not the owner so I'm going to tag @danich1 who is!

**Comment by danich1** [comment]
Greetings Alex, 
I believe your problem is an OS version issue. For linux things work fine, but not surprised MacOS is having issues. I think the quick fix for this situation is to move gensim and sqlalchemy onto the pip section and let pip handle the versioning. 

Correct file (note the environment name change):
```yml
name: snorkeling
channels:
  - conda-forge
  - pytorch
dependencies:
- beautifulsoup4=4.6.0
- ipykernel=5.1.2
- ipywidgets=7.5.1
- jupyter=1.0.0
- jupyter_client=5.3.4
- jupyter_console=6.0.0
- jupyter_core=4.6.0
- llvmlite=0.21.0
- lxml==4.1.1
- matplotlib=3.1.1
- neo4j-python-driver==1.3.1
- networkx=2.1
- nltk=3.2.4
- numpy=1.17.2
- pandas=0.24.0
- pip=19.2.3
- plotnine=0.5.1
- psycopg2=2.7.3.2
- python=3.6.7
- pytorch=1.1.0
- py4j=0.10.6
- requests=2.18.4
- seaborn=0.9.0
- scikit-image=0.13.1
- scikit-learn=0.21.3
- scipy=1.3.1 
- six=1.12.0
- sqlite=3.30.0
- tensorflow==2.0.0
- tensorboard==2.0.0
- tqdm=4.28.1
- tika=1.15
- xlrd=1.1.0
- xlsxwriter=1.0.4
- pip:
    - gensim==3.8.1
    - hetio==0.2.6
    - matplotlib-venn==0.11.5
    - snorkel==0.9.1
    - spacy==1.10.0
    - sqlalchemy==1.1.13

```

~danich1
